[tools]
uv = "0.10.12"

[tasks.setup]
run = """
uv sync
chmod +x shell/*.sh
./shell/init.sh
"""

[tasks.sv]
run = "./shell/solve.sh"

[tasks.p]
run = "uv run main.py"

[tasks.f]
run = "uv run ruff format main.py"

[tasks.l]
run = "uv run ruff check --fix main.py"